import { Shield, Cpu, Database, Github, Linkedin, Zap, Brain, Layers } from 'lucide-react';
import urviPic from '../assets/Urvi_Pic.jpg';

export default function About() {
  return (
    <div className="min-h-screen pt-24 pb-16 px-6 bg-gray-900">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-white mb-4">About DEEPTRACE</h2>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Advanced AI forensic analysis for detecting deepfakes and synthetic face images
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 mb-16">
          <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 hover:border-blue-500/50 transition-colors">
            <Shield className="w-12 h-12 text-blue-400 mb-4" />
            <h3 className="text-xl font-semibold text-white mb-3">What is DEEPTRACE?</h3>
            <p className="text-gray-300 leading-relaxed">
              DEEPTRACE is a deep learning-based forensic analysis tool designed to detect
              AI-generated face images. It identifies synthetic faces created by GANs and
              diffusion models with high accuracy.
            </p>
          </div>

          <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 hover:border-cyan-500/50 transition-colors">
            <Cpu className="w-12 h-12 text-cyan-400 mb-4" />
            <h3 className="text-xl font-semibold text-white mb-3">Technology Stack</h3>
            <p className="text-gray-300 leading-relaxed">
              Built with PyTorch and optimized for GPU acceleration using CUDA. The system
              employs convolutional neural networks trained on extensive datasets of real
              and synthetic faces.
            </p>
          </div>

          <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 hover:border-blue-500/50 transition-colors">
            <Database className="w-12 h-12 text-blue-400 mb-4" />
            <h3 className="text-xl font-semibold text-white mb-3">Detection Capabilities</h3>
            <p className="text-gray-300 leading-relaxed">
              Detects faces generated by popular GAN architectures and modern diffusion
              models. The system analyzes subtle artifacts and patterns invisible to the
              human eye For best results, ensure the face is clearly visible and framed similar to a passport-size photo.
              Detection accuracy may vary for images generated by tools such as Nano Banana, Ghibli-style generators, or Gemini.
            </p>
          </div>

          <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 hover:border-cyan-500/50 transition-colors">
            <Shield className="w-12 h-12 text-cyan-400 mb-4" />
            <h3 className="text-xl font-semibold text-white mb-3">Research-Based</h3>
            <p className="text-gray-300 leading-relaxed">
              Based on experimental evaluation and research in image forensics. Designed
              for face-level deepfake detection with continuous model improvements.
            </p>
          </div>
        </div>

        <div className="bg-gradient-to-br from-gray-800 to-gray-900 rounded-xl p-8 border border-gray-700">
          <div className="text-center mb-8">
            <h3 className="text-2xl font-bold text-white mb-2">Author</h3>
            <div className="w-20 h-1 bg-gradient-to-r from-blue-500 to-cyan-500 mx-auto rounded-full"></div>
          </div>

          <div className="max-w-2xl mx-auto">
            <div className="text-center mb-8">
              <div className="mb-6 flex justify-center">
                <div className="w-32 h-32 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-full p-1">
                  <div className="w-full h-full bg-gray-800 rounded-full overflow-hidden">
                    <img src={urviPic} alt="Urvi Kava" className='w-full h-full object-cover' />
                  </div>
                </div>
              </div>
              <h4 className="text-3xl font-bold text-white mb-2">Urvi Kava</h4>
              <p className="text-blue-400 font-semibold text-lg mb-1">Data Scientist</p>
              <p className="text-gray-400">M.Sc. Data Science, DA-IICT</p>
            </div>

            <div className="bg-gray-800/50 rounded-lg p-6 mb-6">
              <h5 className="text-sm font-semibold text-gray-300 mb-4 uppercase tracking-wider">Technical Expertise</h5>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                <div className="flex items-center gap-2 bg-gray-700/50 rounded-lg p-3 hover:bg-gray-700 transition-colors border border-blue-500/20">
                  <Brain className="w-5 h-5 text-blue-400 flex-shrink-0" />
                  <span className="text-white font-medium">Deep Learning</span>
                </div>
                <div className="flex items-center gap-2 bg-gray-700/50 rounded-lg p-3 hover:bg-gray-700 transition-colors border border-blue-500/20">
                  <Zap className="w-5 h-5 text-cyan-400 flex-shrink-0" />
                  <span className="text-white font-medium">PyTorch</span>
                </div>
                <div className="flex items-center gap-2 bg-gray-700/50 rounded-lg p-3 hover:bg-gray-700 transition-colors border border-blue-500/20">
                  <Cpu className="w-5 h-5 text-green-400 flex-shrink-0" />
                  <span className="text-white font-medium">CUDA</span>
                </div>
                <div className="flex items-center gap-2 bg-gray-700/50 rounded-lg p-3 hover:bg-gray-700 transition-colors border border-cyan-500/20">
                  <Layers className="w-5 h-5 text-purple-400 flex-shrink-0" />
                  <span className="text-white font-medium">CNNs</span>
                </div>
                <div className="flex items-center gap-2 bg-gray-700/50 rounded-lg p-3 hover:bg-gray-700 transition-colors border border-cyan-500/20">
                  <Shield className="w-5 h-5 text-red-400 flex-shrink-0" />
                  <span className="text-white font-medium">Image Forensics</span>
                </div>
                <div className="flex items-center gap-2 bg-gray-700/50 rounded-lg p-3 hover:bg-gray-700 transition-colors border border-blue-500/20">
                  <Database className="w-5 h-5 text-orange-400 flex-shrink-0" />
                  <span className="text-white font-medium">FastAPI</span>
                </div>
              </div>
            </div>

            <div className="flex justify-center gap-4">
              <a
                href="https://github.com/Urvikawa31"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 bg-gray-700 hover:bg-gray-600 text-white px-6 py-3 rounded-lg font-semibold transition-all transform hover:scale-105"
              >
                <Github className="w-5 h-5" />
                GitHub
              </a>
              <a
                href="https://www.linkedin.com/in/urvikava31/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-6 py-3 rounded-lg font-semibold transition-all transform hover:scale-105"
              >
                <Linkedin className="w-5 h-5" />
                LinkedIn
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
